# Intro to Bayesian Statistics Lab

Complete the following set of exercises to solidify your knowledge of Bayesian statistics and Bayesian data analysis.

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Cookie Problem

Suppose we have two bowls of cookies. Bowl 1 contains 30 vanilla cookies and 10 chocolate cookies. Bowl 2 contains 20 of each. You randomly pick one cookie out of one of the bowls, and it is vanilla. Use Bayes Theorem to calculate the probability that the vanilla cookie you picked came from Bowl 1?

In [21]:
priorsv = [1 / 2, 1 / 2]
likelihoodsv = [30 / 40, 20 / 20]
def bayes_rule(priorsv, likehoodsv):
    margv = sum(np.multiply(priorsv, likelihoodsv))
    postv = np.divide(np.multiply(priorsv, likelihoodsv), margv)
    return postv
bayes_rule(priorsv, likelihoodsv)


array([0.42857143, 0.57142857])

In [22]:
bowl_1v = round(bayes_rule(priorsv, likelihoodsv)[0],3)
print("The probability that the vanilla cookie I picked came from Bowl 1 is {}".format(bowl_1v))


The probability that the vanilla cookie I picked came from Bowl 1 is 0.429


What is the probability that it came from Bowl 2?

In [23]:
bowl_2v = round(bayes_rule(priorsv, likelihoodsv)[1],3)
print("The probability that the vanilla cookie I picked came from Bowl 2 is {}".format(bowl_2v))


The probability that the vanilla cookie I picked came from Bowl 2 is 0.571


What if the cookie you had picked was chocolate? What are the probabilities that the chocolate cookie came from Bowl 1 and Bowl 2 respectively?

In [29]:
priorsc = [1 / 2, 1 / 2]
likelihoodsc = [10 / 40, 20 / 20]
def bayes_rule(priorsc, likehoodsc):
    margc = sum(np.multiply(priorsc, likelihoodsc))
    postc = np.divide(np.multiply(priorsc, likelihoodsc), margc)
    return postc
bayes_rule(priorsc, likelihoodsc)


array([0.2, 0.8])

In [30]:
bowl_1c = round(bayes_rule(priorsc, likelihoodsc)[0],3)
print("The probability that the chocolate cookie I picked came from Bowl 1 is {}".format(bowl_1c))


The probability that the chocolate cookie I picked came from Bowl 1 is 0.2


In [31]:
bowl_2c = round(bayes_rule(priorsc, likelihoodsc)[1],3)
print("The probability that the chocolate cookie I picked came from Bowl 2 is {}".format(bowl_2c))


The probability that the chocolate cookie I picked came from Bowl 2 is 0.8


## 2. Candy Problem

Suppose you have two bags of candies:

- In Bag 1, the mix of colors is:
    - Brown - 30%
    - Yellow - 20%
    - Red - 20%
    - Green - 10%
    - Orange - 10%
    - Tan - 10%
    
- In Bag 2, the mix of colors is:
    - Blue - 24%
    - Green - 20%
    - Orange - 16%
    - Yellow - 14%
    - Red - 13%
    - Brown - 13%
    
Not knowing which bag is which, you randomly draw one candy from each bag. One is yellow and one is green. What is the probability that the yellow one came from the Bag 1?

*Hint: For the likelihoods, you will need to multiply the probabilities of drawing yellow from one bag and green from the other bag and vice versa.*

In [35]:
priorsy = [1 / 2, 1 / 2]
likelihoodsy = [(2 / 10)*(2 / 10),(1 / 10)*(14 / 100)]
def bayes_rule(priorsy, likehoodsy):
    margy = sum(np.multiply(priorsy, likelihoodsy))
    posty = np.divide(np.multiply(priorsy, likelihoodsy), margy)
    return posty
bayes_rule(priorsy, likelihoodsy)


array([0.74074074, 0.25925926])

What is the probability that the yellow candy came from Bag 2?

In [36]:
bag_2y = round(bayes_rule(priorsy, likelihoodsy)[1],3)
print("The probability that the yellow candy I picked came from Bag 2 is {}".format(bag_2y))


The probability that the yellow candy I picked came from Bag 2 is 0.259


What are the probabilities that the green one came from Bag 1 and Bag 2 respectively?

In [37]:
priorsg = [1 / 2, 1 / 2]
likelihoodsg = [(1 / 10)*(14 / 100),(2 / 100)*(2 / 100)]
def bayes_rule(priorsg, likehoodsg):
    margg = sum(np.multiply(priorsg, likelihoodsg))
    postg = np.divide(np.multiply(priorsg, likelihoodsg), margg)
    return postg
bayes_rule(priorsg, likelihoodsg)


array([0.97222222, 0.02777778])

In [38]:
bag_1g = round(bayes_rule(priorsg, likelihoodsg)[0],3)
print("The probability that the green candy I picked came from Bag 2 is {}".format(bag_1g))


The probability that the green candy I picked came from Bag 2 is 0.972


In [39]:
bag_2g = round(bayes_rule(priorsg, likelihoodsg)[1],3)
print("The probability that the green candy I picked came from Bag 2 is {}".format(bag_2g))

The probability that the green candy I picked came from Bag 2 is 0.028


## 3. Monty Hall Problem

Suppose you are a contestant on the popular game show *Let's Make a Deal*. The host of the show (Monty Hall) presents you with three doors - Door A, Door B, and Door C. He tells you that there is a sports car behind one of them and if you choose the correct one, you win the car!

You select Door A, but then Monty makes things a little more interesting. He opens Door B to reveal that there is no sports car behind it and asks you if you would like to stick with your choice of Door A or switch your choice to Door C. Given this new information, what are the probabilities of you winning the car if you stick with Door A versus if you switch to Door C?

## 4. Bayesian Analysis 

Suppose you work for a landscaping company, and they want to advertise their service online. They create an ad and sit back waiting for the money to roll in. On the first day, the ad sends 100 visitors to the site and 14 of them sign up for landscaping services. Create a generative model to come up with the posterior distribution and produce a visualization of what the posterior distribution would look like given the observed data.

Produce a set of descriptive statistics for the posterior distribution.

What is the 90% credible interval range?

What is the Maximum Likelihood Estimate?